FROM jenkins/jenkins:lts

USER root

# Install Node.js + npm
RUN apt-get update \
 && apt-get install -y curl ca-certificates gnupg \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get install -y nodejs \
 && npm --version

USER jenkins
